version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: next-pwa
    versions:
    - 5.1.4
    - 5.2.1
    - 5.2.14
    - 5.2.3
    - 5.2.5
    - 5.2.9
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.1.18
    - 6.1.19
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.7
    - 6.2.8
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.18
    - 6.1.19
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.7
    - 6.2.8
  - dependency-name: "@babel/core"
    versions:
    - 7.12.17
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.1
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: next
    versions:
    - 10.0.9
    - 10.1.1
    - 10.1.2
    - 10.1.3
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
  - dependency-name: styled-components
    versions:
    - 5.2.2
  - dependency-name: eslint
    versions:
    - 7.21.0
    - 7.22.0
    - 7.23.0
  - dependency-name: husky
    versions:
    - 5.1.0
    - 5.1.2
    - 5.2.0
    - 6.0.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.28
    - 14.14.30
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.1
    - 4.18.0
    - 4.19.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
  - dependency-name: "@types/styled-components"
    versions:
    - 5.1.8
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.17
